default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tsubuyaku_development

test:
  <<: *default
  database: tsubuyaku_test

production:
  <<: *default
  database: tsubuyaku_production
  username: tsubuyaku
  password: <%= ENV['TSUBUYAKU_DATABASE_PASSWORD'] %>
